version: '2.1'
  services:
      gateway-proxy:
        image: 12233arquitectura/1b_gateway_proxy
        depends_on:
          - gateway-api
        ports:
          - 80:80
      gateway-api:
        image: 12233arquitectura/1b_gateway_api
        environment:
          PORT: '5000'
          SHOW_URLS: 'true'
          USERS_PORT: '4004'
          USERS_ENTRY: 'users/'
          AUTH_PORT: '4004'
          AUTH_ENTRY: 'ldap/'
       users-db:
        image: mysql:5.7.22
        ports:
          - "3304:3304"
        environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_USER: db_users_user
          MYSQL_PASSWORD: 123
          MYSQL_DATABASE: db_users
          MYSQL_HOST: users-db
       users-ms:
        image: 12233arquitectura/1b_users_ms
        command: bash -c "sleep 80 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4004 -b '0.0.0.0'"
        environment:
          PORT: '4004'
        depends_on:
          - users-db
      openldap:
        image: osixia/openldap:1.1.8
        container_name: openldap
        environment:
          COMPOSE_HTTP_TIMEOUT: 200
          LDAP_LOG_LEVEL: "256"
          LDAP_ORGANISATION: "PC UN"
          LDAP_DOMAIN: "pcun.com"
          LDAP_BASE_DN: ""
          LDAP_ADMIN_PASSWORD: "admin"
          LDAP_CONFIG_PASSWORD: "config"
          LDAP_READONLY_USER: "false"
          #LDAP_READONLY_USER_USERNAME: "readonly"
          #LDAP_READONLY_USER_PASSWORD: "readonly"
          LDAP_BACKEND: "hdb"
          LDAP_TLS: "true"
          LDAP_TLS_CRT_FILENAME: "ldap.crt"
          LDAP_TLS_KEY_FILENAME: "ldap.key"
          LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
          LDAP_TLS_ENFORCE: "false"
          LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
          LDAP_TLS_PROTOCOL_MIN: "3.1"
          LDAP_TLS_VERIFY_CLIENT: "demand"
          LDAP_REPLICATION: "false"
          #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
          #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
          #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
          LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
          LDAP_SSL_HELPER_PREFIX: "ldap"
        tty: true
        stdin_open: true
        volumes:
          - /var/lib/ldap
          - /etc/ldap/slapd.d
          - /container/service/slapd/assets/certs/
        ports:
          - "389:389"
          - "636:636"
        hostname: "pcun.com"
      phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        environment:
          PHPLDAPADMIN_LDAP_HOSTS: "openldap"
          PHPLDAPADMIN_HTTPS: "false"
        ports:
          - "8085:80"
        links:
          - openldap
